version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "10000:10000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
