services:
  - type: web
    name: careplant-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile 
    buildCommand: npm install && npm run build
    plan: free

  - type: web
    name: careplant-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    plan: free
